/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, inpOutNgCreateDevice)
#endif

NTSTATUS
inpOutNgCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    PNP_BUS_INFORMATION        busInfo;
    WDFDEVICE device;
    NTSTATUS status;

//!!    PDEVICE_OBJECT deviceObject;
//!!    NTSTATUS status;

    WCHAR NameBuffer[] = L"\\Device\\inpoutng";

    UNICODE_STRING uniNameString;

    PAGED_CODE();

    //
    // Initialize WPP Tracing
    //
    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DEVICE, "%!FUNC! Entry");

    WdfDeviceInitSetDeviceType(DeviceInit, FILE_DEVICE_BUS_EXTENDER);
    WdfDeviceInitSetExclusive(DeviceInit, TRUE);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {

        RtlInitUnicodeString(&uniNameString, NameBuffer);

        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = inpOutNgGetContext(device);

        //
        // Initialize the context.
        //
        deviceContext->Device = device;
        deviceContext->HwErrCount = 0;

        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_INPOUTNG,
            NULL // ReferenceString
            );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = inpoutngQueueInitialize(device);
        }

        //
        // This value is used in responding to the IRP_MN_QUERY_BUS_INFORMATION
        // for the child devices. This is an optional information provided to
        // uniquely idenitfy the bus the device is connected.
        //
        busInfo.BusTypeGuid = GUID_DEVCLASS_SYSTEM;
        busInfo.LegacyBusType = PNPBus;
        busInfo.BusNumber = 0;

        WdfDeviceSetBusInformationForChildren(device, &busInfo);
        
        //Create ISR…
        //
        status = inpOutNgInterruptCreate(deviceContext);

        if (!NT_SUCCESS(status)) {
            TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "WdfDeviceCreate ISR creation failed %!STATUS!", status);
            return status;
        }

        status = WdfDeviceCreateSymbolicLink(device, &uniNameString);
        if (!NT_SUCCESS(status)) {
            TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "WdfDeviceCreate NT name creation failed %!STATUS!", status);
        }
    }

    return status;
}
