/*++

Module Name:

    public.h

Abstract:

    This module contains the common declarations shared by driver
    and user applications.

Environment:

    user and kernel

--*/

#pragma once

#include "inpout_types.h"

EXTERN_C_START
//
// Define an Interface Guid so that apps can find the device and talk to it.
//
DEFINE_GUID (GUID_DEVINTERFACE_INPOUTNG,
    0xf3c34686,0xe4e8,0x43db,0xb3,0x8a,0xad,0xef,0xc6,0xda,0x58,0x51);
// {f3c34686-e4e8-43db-b38a-adefc6da5851}

DEFINE_GUID(GUID_DEVCLASS_SYSTEM,
    0x4d36e97d, 0xe325, 0x11ce, 0xbf, 0xc1, 0x08, 0x00, 0x2b, 0xe1, 0x03, 0x18);
// {4d36e97d-e325-11ce-bfc1-08002be10318}

#define FILE_INPOUTNG 40000
#define IOCTL_READ_PORT_UCHAR	    CTL_CODE(FILE_INPOUTNG, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_PORT_UCHAR	    CTL_CODE(FILE_INPOUTNG, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_PORT_USHORT	    CTL_CODE(FILE_INPOUTNG, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_PORT_USHORT	    CTL_CODE(FILE_INPOUTNG, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_PORT_ULONG	    CTL_CODE(FILE_INPOUTNG, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WRITE_PORT_ULONG	    CTL_CODE(FILE_INPOUTNG, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_REGISTER_IRQ          CTL_CODE(FILE_INPOUTNG, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TEST_ASYNC            CTL_CODE(FILE_INPOUTNG ,0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_DRVINFO           CTL_CODE(FILE_INPOUTNG ,0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_IRQCOUNT          CTL_CODE(FILE_INPOUTNG ,0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_IRQCLEAR          CTL_CODE(FILE_INPOUTNG ,0x813, METHOD_BUFFERED, FILE_ANY_ACCESS)

EXTERN_C_END
